protobuf_sources(
  name="protobuf"
)

resource(
  name="aresource",
  source="a-resource-file"
)

tutu_sources(
  name="tutu",
  sources=["*.yaml"]
)

python_requirement(
  name="reqs-protobuf",
  requirements=[
      "grpcio==1.47.0",
      "protobuf==4.21.4"
  ]
)
