protobuf_sources(
  name="protobuf"
)

tutu_sources(
  name="tutu",
  sources=["*.yaml"]
)

python_requirement(
  name="reqs-protobuf",
  requirements=[
      "grpcio==1.32.0",
      "protobuf>=3.12.1"
  ]
)
